### ISSUE TITLE
Needs more documentation for how to setup, contribute, etc.

### ISSUE THREAD

**Issue by jashgala** [cast-bucket/cast-bucket#3]
It's harder to look around this code base without knowing how to build, run it on one's system.

Perhaps, sharing the basic details on the README.md can help and others can then take it forward through PRs?

**Comment by shrirambalaji** [comment]
@jashgala Thanks a ton for your interest in this project :smile: . I have now added some initial setup instructions to build/install but its definitely a WIP. Feel free to reach out or join the slack channel in case you have any questions.
